trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      sudo apt-get update
      sudo apt-get install python2-pip -y
      yum autoremove python2-winrm.noarch
      pip3 install "pywinrm>=0.2.2"
  displayName: 'Install winrm module'
- task: Ansible@0
  inputs:
    ansibleInterface: 'agentMachine'
    playbookPathOnAgentMachine: '$(System.DefaultWorkingDirectory)/ansible_db_env_management_scripts/playbook1.yml'
    inventoriesAgentMachine: 'inlineContent'
    inventoryInlineContentAgentMachine: |
      [win]
      windows2019 ansible_host=20.4.1.2 
      ansible_user=Admin5d29d50f69 
      ansible_password=mAb@*=WOJ0jY*=VDu@5Gjr8=*1ym5B*w! 
      ansible_connection=winrm 
      ansible_winrm_transport=basic
