trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: Ansible@1
  inputs:
    ansibleType: 'Playbook'
    playbook: 'ansible_db_env_management_scripts/playbook1.yml'
    inventory: 'ansible_db_env_management_scripts/inventory'
