trigger: none
###################################################################################################################################################

variables:
  - group: ansible_Refresh_DB_Variables

###################################################################################################################################################

pool:
  vmImage: 'ubuntu-latest'

stages:
# Second stage extract .bacpac db from VmA    
- stage: VmA_export_db
  jobs:
  - job: export_db
    timeoutInMinutes: 350
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          #Install WinRM module for python in controller ubuntu
          python3 -m pip install --user ansible
          pip install pywinrm
    - task: Ansible@0
      inputs:
        ansibleInterface: 'agentMachine'
        playbookPathOnAgentMachine: '$(System.DefaultWorkingDirectory)/ansible_db_env_management_scripts/playbook1.yml'
        inventoriesAgentMachine: 'file'
        inventoryFileOnAgentMachine: '$(System.DefaultWorkingDirectory)/ansible_db_env_management_scripts/inventory'
        extraVars: '-e script1_path=$(script1_path)'' 
    

      
