trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      sudo apt-get update
      sudo apt-get install python3-pip -y
      pip3 install pywinrm
  displayName: 'Install winrm module'
- task: Ansible@0
  inputs:
    ansibleInterface: 'agentMachine'
    playbookPathOnAgentMachine: 'ansible_db_env_management_scripts/playbook1.yml'
    inventoriesAgentMachine: 'file'
    inventoryFileOnAgentMachine: 'ansible_db_env_management_scripts/inventory'
