trigger:
- none

pool:
  vmImage: 'windows-latest'

steps:
- task: Ansible@0
  inputs:
    ansibleInterface: 'agentMachine'
    playbookPathOnAgentMachine: 'ansible_db_env_management_scripts/playbook1.yml'
    inventoriesAgentMachine: 'file'
    inventoryFileOnAgentMachine: 'ansible_db_env_management_scripts/inventory'