trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      sudo apt-get update
      sudo apt-get install python2-pip -y
      yum autoremove python2-winrm.noarch
      pip3 install "pywinrm>=0.2.2"
  displayName: 'Install winrm module'
- task: Ansible@0
  inputs:
    ansibleVersion: '2.10'
    playbookPath: '$(Build.Repository.LocalPath)/ansible_db_env_management_scripts/playbook1.yml'
    inventory: '$(Build.Repository.LocalPath)/ansible_db_env_management_scripts/inventory'
  
