trigger: none
###################################################################################################################################################

variables:
  - group: ansible_Refresh_DB_Variables

###################################################################################################################################################

pool:
  vmImage: 'ubuntu-latest'

stages:
# Second stage extract .bacpac db from VmA    
- stage: VmA_export_db
  jobs:
  - job: export_db
    timeoutInMinutes: 350
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          #Install WinRM module for python in controller ubuntu
          python3 -m pip install --user ansible
          pip install pywinrm
    - task: Ansible@0
      inputs:
        ansibleInterface: 'agentMachine'
        playbookPathOnAgentMachine: '$(System.DefaultWorkingDirectory)/ansible_db_env_management_scripts/playbook1.yml'
        inventoriesAgentMachine: 'file'
        inventoryFileOnAgentMachine: '$(System.DefaultWorkingDirectory)/ansible_db_env_management_scripts/inventory'
        extraVars: -e script1_path = "db_env_managment_scripts/upload_db.ps1" -e db_path = "C:/Bacpacs/" -e db_name="db_dev_1.bacpac" -e url='https://apsiaem01ada09a20ec1a713.blob.core.windows.net/retail-cdx-down-68719476736?sp=racwdli&st=2022-10-19T10:51:08Z&se=2023-02-02T19:51:08Z&spr=https&sv=2021-06-08&sr=c&sig=kiGgyozma%2FZWom%2BtWz%2F7ynf8rEoXCn3XP5DjigiS65Q%3D'
    

      
