trigger: none
###################################################################################################################################################

variables:
  - group: Refresh_DB_Variables

###################################################################################################################################################

pool:
  vmImage: 'ubuntu-latest'

stages:
# Second stage extract .bacpac db from VmA    
- stage: VmA_export_db
  jobs:
  - job: export_db
    timeoutInMinutes: 350
    steps:
    - checkout: self
    - task: CmdLine@2
      inputs:
        script: |
          #Install WinRM module for python in controller ubuntu
          python3 -m pip install --user ansible
          pip install pywinrm
          ls
    - task: Ansible@0
      inputs:
        ansibleInterface: 'agentMachine'
        playbookPathOnAgentMachine: '$(System.DefaultWorkingDirectory)/ansible_db_env_management_scripts/playbook1.yml'
        inventoriesAgentMachine: 'file'
        inventoryFileOnAgentMachine: '$(System.DefaultWorkingDirectory)/ansible_db_env_management_scripts/inventory'
        args: -vvv --extra-vars="upload_db_script='$(System.DefaultWorkingDirectory)/$(script_upload_db)' extract_db_path='$(extract_db_path)' db_name='$(db_name)' blob_url='$(blob_url | Replace('=','='))'"
    
      
