# Maven

stages:
- stage: uatBacpacToAzureBlob
  jobs:
  - job: extractDbAndUploadToAzureBlob
    pool:
      name: Nodepool
      demands:
        - agent.name -equals uat_simulation_agent
    steps:
    - task: PowerShell@2
      inputs:
        filePath: './db_env_managment_scripts/export_db_to_bacpac.ps1'
    - task: PowerShell@2
      inputs:
        filePath: 'db_env_managment_scripts/upload_bacpac_to_azureblob.ps1'

- stage: bacpacFromAzureToTier1Import
  jobs:
  - job: downloadBacpacAndImportIntoDb
    pool:
      name: Nodepool
      demands:
        - agent.name -equals tier1_agent
    steps:
    - task: PowerShell@2
      inputs:
        filePath: './db_env_managment_scripts/download_bacpac_from_azureblob.ps1'
    - task: PowerShell@2
      inputs:
        filePath: 'db_env_managment_scripts/import_db_from_bacpac.ps1'

         


