variables:
- name: extract_db_path
  value: "C:/Bacpacs/" 
- name: db_name
  value: "db_dev_1.bacpac"

stages:
- stage: setUpEnvironments
  jobs:
  - job: setUpUAT
    timeoutInMinutes: 360
    pool:
      name: Nodepool
      demands:
        - agent.name -equals uat_simulation_agent
    steps:
    - task: PowerShell@2
      inputs:
        filePath: './db_env_managment_scripts/install_env_dependencies.ps1'
  - job: setUpTier1
    timeoutInMinutes: 360
    pool:
      name: Nodepool
      demands:
        - agent.name -equals tier1_agent 
    steps:
    - task: PowerShell@2
      inputs:
        filePath: './db_env_managment_scripts/install_env_dependencies.ps1'
    

- stage: VM_A database to Azure Storage
  jobs:
  - job: extract_and_upload
    timeoutInMinutes: 360
    pool:
      name: Nodepool
      demands:
        - agent.name -equals uat_simulation_agent
    steps:
    - task: PowerShell@2
      inputs:
        arguments: '${{variables.extract_db_path}} ${{variables.db_name}}'
        filePath: './db_env_managment_scripts/export_db.ps1'
    - task: PowerShell@2
      inputs:
        filePath: 'db_env_managment_scripts/upload_bacpac_to_azureblob.ps1'

- stage: bacpacFromAzureToTier1Import
  jobs:
  - job: downloadBacpacAndImportIntoDb
    timeoutInMinutes: 360
    pool:
      name: Nodepool
      demands:
        - agent.name -equals tier1_agent
    steps:
    - task: PowerShell@2
      inputs:
        filePath: './db_env_managment_scripts/download_bacpac_from_azureblob.ps1'
    - task: PowerShell@2
      inputs:
        filePath: 'db_env_managment_scripts/import_db_from_bacpac.ps1'

         


