 
variables:
  - group: Setup_environments_variables
  
#################################################################################################################################################

stages:
# First stage checks if NuGet, df365.tools are installed and the needed packages as d365sqlpackage and d365AzCopy 
- stage: Set_environments
  jobs:
  - job: set_VmA
    timeoutInMinutes: $[variables['jobs_timeout']]
    pool:
      name: ${{variables.pool}}
      demands:
        - agent.name -equals ${{variables.agent_A}}
    steps:
    - task: PowerShell@2
      inputs:
        arguments: "${{variables.agent_path}} ${{variables.startup_scripts_path}} ${{variables.policy_script_path}} ${{variables.powershell_path}}"
        filePath: ${{variables.script_set_environments}}
  - job: set_VmB
    timeoutInMinutes: $[variables['jobs_timeout']]
    pool:
      name: ${{variables.pool}}
      demands:
        - agent.name -equals ${{variables.agent_B}}
    steps:
    - task: PowerShell@2
      inputs:
        arguments: "${{variables.agent_path}} ${{variables.startup_scripts_path}} ${{variables.policy_script_path}} ${{variables.powershell_path}}"
        filePath: ${{variables.script_set_environments}}
