 
variables:
  - group: Setup_environments_variables
  
#################################################################################################################################################

stages:
# First stage checks if NuGet, df365.tools are installed and the needed packages as d365sqlpackage and d365AzCopy 
- stage: Set_environments
  jobs:
  - job: set_VmA
    timeoutInMinutes: $[variables['jobs_timeout']]
    pool:
      name: $(pool)
      demands:
        - agent.name -equals $(agent_a)
    steps:
    - task: PowerShell@2
      inputs:
        arguments: "$(agent_path) $(startup_scripts_path) $(policy_script_path) $(powershell_path)"
        filePath: $(script_set_environments)
  - job: set_VmB
    timeoutInMinutes: $[variables['jobs_timeout']]
    pool:
      name: $(pool)
      demands:
        - agent.name -equals $(agent_b)
    steps:
    - task: PowerShell@2
      inputs:
        arguments: "$(agent_path) $(startup_scripts_path) $(policy_script_path) $(powershell_path)"
        filePath: $(script_set_environments)
  
