# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

# Define the pool where the pipeline will run
pool:
  vmImage: 'windows-latest'

# Define the steps of the pipeline
steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'Sottoscrizione di Visual Studio Enterprise - MPN(c36034cc-afa8-419f-9f57-7a7221a30b58)'
    ScriptType: 'FilePath'
    ScriptPath: '$(System.DefaultWorkingDirectory)/ansible_db_env_management_scripts/set_environments.ps1'
    ScriptArguments: '-VMName deve4f2cbff76-1 -ResourceGroupName apsiaem01 -ComputerName deve4f2cbff76-1'
    azurePowerShellVersion: LatestVersion
