trigger: 
- none

variables:
  - group: ansible_Setup_environments_variables
  
#################################################################################################################################################

stages:
# This stage sets inbound rules ofr network security group associated with vma and vmb to allow connection on WinRM port  
- stage: Set_network_security_group_rule
  jobs:
  - job: set_nsg_rule_VmA_VmB
    timeoutInMinutes: $[variables['jobs_timeout']]
    pool:
     vmImage: 'windows-latest'
    steps:
    - task: AzurePowerShell@5
      displayName: Setting azure nsg for VmA
      inputs:
        azureSubscription: $(VmA_azure_subscription)
        ScriptType: 'FilePath'
        ScriptPath: $(set_azure_In_nsg_rule_script)
        ScriptArguments: -resourceGroupName $(VmA_resourceGroupName) -networkSecurityGroupName $(VmA_nsg_name) -ruleName $(rule_name) -destinationPort $(destination_port)
        azurePowerShellVersion: LatestVersion
    - task: AzurePowerShell@5
      displayName: Setting azure nsg for VmB
      inputs:
        azureSubscription: $(VmB_azure_subscription)
        ScriptType: 'FilePath'
        ScriptPath: $(set_azure_In_nsg_rule_script)
        ScriptArguments: -resourceGroupName $(VmB_resourceGroupName) -networkSecurityGroupName $(VmB_nsg_name) -ruleName $(rule_name) -destinationPort $(destination_port)
        azurePowerShellVersion: LatestVersion
# This stage checks if NuGet, df365.tools are installed and the needed packages as d365sqlpackage and d365AzCopy. Also sets winRM for ansible to reach hosts
- stage: Set_environments
  jobs:
  - job: set_VmA
    timeoutInMinutes: $[variables['jobs_timeout']]
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: AzurePowerShell@5
      displayName: Setting VmA
      inputs:
         azureSubscription: $(VmA_azure_subscription)
         ScriptType: 'FilePath'
         ScriptPath: $(set_environments_script)
         ScriptArguments: -vmName $(VmA_azure_name) -resourceGroupName $(VmA_resourceGroupName)
         azurePowerShellVersion: LatestVersion
#  - job: set_VmB
#    timeoutInMinutes: $[variables['jobs_timeout']]
#    pool:
#      vmImage: 'windows-latest'
#    steps:
#    - task: AzurePowerShell@5
#      displayName: Setting VmB
#      inputs:
#        azureSubscription: $(azure_subscription)
#        ScriptType: 'FilePath'
#        ScriptPath: $(set_environments_script)
#        ScriptArguments: -vmName $(VmB_azure_name) -resourceGroupName $(VmB_resourceGroupName)
#        azurePowerShellVersion: LatestVersion

