trigger: none

variables:
  - group: ansible_setup_prova
  
#################################################################################################################################################

stages:
# First stage checks if NuGet, df365.tools are installed and the needed packages as d365sqlpackage and d365AzCopy. Also sets winRM for ansible to reach hosts
- stage: Set_environments
  jobs:
  - job: set_VmA
    timeoutInMinutes: $[variables['jobs_timeout']]
    pool:
      vmImage: 'windows-latest'
    steps:
    - - task: AzurePowerShell@5
        displayName: Setting VmA
        inputs:
          azureSubscription: $(azure_subscription)
          ScriptType: 'FilePath'
          ScriptPath: $(set_environments_script)
          ScriptArguments: -vmName $(VmA_azure_name) -resourceGroupName $(VmA_resourceGroupName)
          azurePowerShellVersion: LatestVersion
#  - job: set_VmB
#    timeoutInMinutes: $[variables['jobs_timeout']]
#    pool:
#      vmImage: 'windows-latest'
#    steps:
#    - - task: AzurePowerShell@5
#        displayName: Setting VmB
#        inputs:
#          azureSubscription: $(azure_subscription)
#          ScriptType: 'FilePath'
#          ScriptPath: $(set_environments_script)
#          ScriptArguments: -vmName $(VmB_azure_name) -resourceGroupName $(VmB_resourceGroupName)
#          azurePowerShellVersion: LatestVersion

