trigger: none

parameters:
- name: agent_id
  displayName: agent id
  default: noValue
  type: string

- name: video_or_screenshot
  displayName: agent id
  default: noValue
  type: string

- name: ticket_id
  displayName: agent id
  default: noValue
  type: string

# ---------------------------------------------------------------------
variables:
- name: pool
  value: "Users"

# ---------------------------------------------------------------------

stages:
# Se  
- stage: Stage_${{parameters.agent_id}}
  jobs:
  - job: job_1
    timeoutInMinutes: 300
    pool:
      name: ${{variables.pool}}
      demands:
        - agent.name -equals ${{parameters.agent_id}}
    steps:
    - task: PowerShell@2
      inputs:
        arguments: '${{parameters.video_or_screenshot}} $(blob_url) ${{parameters.ticket_id}}'
        filePath: 'db_env_managment_scripts/prova.ps1'
