
parameters:
- name: agent_id
  displayName: agent id
  default: noValue
  type: string

# ---------------------------------------------------------------------
variables:
   - template: variable-template.yml

# ---------------------------------------------------------------------

stages:
# Se  
- stage: Stage_${{parameters.agent_id}}
  jobs:
  - job: job_1
    timeoutInMinutes: 300
    pool:
      name: ${{variables.pool}}
      demands:
        - agent.name -equals ${{parameters.agent_id}}
    steps:
    - task: PowerShell@2
      inputs:
        filePath: 'db_env_managment_scripts/prova.ps1'
