trigger: none



parameters:
- name: agent_id
  displayName: a
  default: noValue
  type: string

- name: video_or_screenshot
  displayName: aa
  default: noValue
  type: string

- name: ticket_id
  displayName: aaa
  default: noValue
  type: string

- name: test_env_url
  displayName: aaaaa
  default: "www.google.com"
  type: string


# ---------------------------------------------------------------------
variables:
  - group: Setup_environments_variables

# ---------------------------------------------------------------------

stages:
# Se  
- stage: Stage_${{parameters.agent_id}}
  jobs:
  - job: job_1
    timeoutInMinutes: 300
    pool:
      name: $(pool)
      demands:
        - agent.name -equals ${{parameters.agent_id}}
    steps:
    - task: PowerShell@2
      inputs:
        arguments: "${{parameters.test_env_url}} ${{parameters.ticket_id}} ${{parameters.video_or_screenshot}} '$(blob_url)'"
        filePath: 'db_env_managment_scripts/prova.ps1'
