trigger: none



parameters:
- name: agent_id
  displayName: a
  default: noValue
  type: string

- name: video_or_screenshot
  displayName: aa
  default: noValue
  type: string

- name: ticket_id
  displayName: aaa
  default: noValue
  type: string

- name: test_env_url
  displayName: aaaaa
  default: "https://devtestgiliebe02a3ff67b3b5edevaos.axcloud.dynamics.com/?cmp=ITCO%26mi=DefaultDashboard"
  type: string

name: ${{parameters.ticket_id}}

# ---------------------------------------------------------------------
variables:
  - group: User_variables

# ---------------------------------------------------------------------

stages:
# Se  
- stage: Stage_${{parameters.agent_id}}
  dependsOn: []
  jobs:
  - job: job_1
    timeoutInMinutes: 300
    pool:
      name: $(pool)
      demands:
        - agent.name -equals ${{parameters.agent_id}}
    steps:
    - task: PowerShell@2
      displayName: Making ${{parameters.video_or_screenshot}}
      inputs:
        arguments: "${{parameters.test_env_url}} ${{parameters.ticket_id}} ${{parameters.video_or_screenshot}} '$(blob_url)'"
        filePath: 'user_client_scripts/record.ps1'
    - task: PowerShell@2
      displayName: Uploading ${{parameters.video_or_screenshot}}
      inputs:
        arguments: "${{parameters.ticket_id}} '$(blob_url)'"
        filePath: 'user_client_scripts/upload_file.ps1'
