
parameters:
- name: agent_id
  displayName: agent id
  default: noValue
  type: string

# ---------------------------------------------------------------------
variables:
# Name of agent-pool 
- name: pool
  value: "Users"

# ---------------------------------------------------------------------

stages:
# Second stage extract .bacpac db from VmA    
- stage: Stage_1
  jobs:
  - job: job_1
    timeoutInMinutes: ${{variables.jobs_timeout}}
    pool:
      name: ${{variables.pool}}
      demands:
        - agent.name -equals '${{parameters.agent_id}}'
    steps:
    - task: PowerShell@2
      inputs:
        filePath: 'db_env_managment_scripts/prova.ps1'
