trigger: none

parameters:
- name: agent_id
  displayName: a
  default: noValue
  type: string

- name: video_or_screenshot
  displayName: aa
  default: noValue
  type: string

- name: ticket_id
  displayName: aaa
  default: noValue
  type: string

- name: test_env_url
  displayName: aaaaa
  default: "www.google.com"
  type: string

- name: blob_url
  displayName: aaaaa
  default: 'https://apsiaem01ada09a20ec1a713.blob.core.windows.net/retail-cdx-down-68719476736?sp=racwdli&st=2022-10-19T10:51:08Z&se=2023-02-02T19:51:08Z&spr=https&sv=2021-06-08&sr=c&sig=kiGgyozma%2FZWom%2BtWz%2F7ynf8rEoXCn3XP5DjigiS65Q%3D'
  type: string
  
# ---------------------------------------------------------------------
variables:
- name: pool
  value: "Users"

# ---------------------------------------------------------------------

stages:
# Se  
- stage: Stage_${{parameters.agent_id}}
  jobs:
  - job: job_1
    timeoutInMinutes: 300
    pool:
      name: ${{variables.pool}}
      demands:
        - agent.name -equals ${{parameters.agent_id}}
    steps:
    - task: PowerShell@2
      inputs:
        arguments: "${{parameters.test_env_url}} ${{parameters.ticket_id}} ${{parameters.video_or_screenshot}} '${{parameters.blob_url}}'"
        filePath: 'db_env_managment_scripts/prova.ps1'
