- name: Export and upload database from VmA
  hosts: windows
  become: false
  gather_facts: false
  tasks:
  - name: Copy script to target VM
    win_copy:
      src: "{{upload_db_script}}"
      dest: "C:/temp/upload_db.ps1"
  - name: Upload db
    win_shell: powershell.exe -File C:/temp/upload_db.ps1 {{ extract_db_path }}{{ db_name }} {{ blob_url }}
    