- name: Export and upload database from VmA
  hosts: VmA_windows
  become: false
  gather_facts: false
  tasks:
  - name: Copy export_db.ps1 to VmA
    win_copy:
      src: "{{ script_export_db }}"
      dest: "C:/Temp/export_db.ps1"
  - name: Copy upload_db.ps1 to VmA
    win_copy:
      src: "{{ script_upload_db }}"
      dest: "C:/Temp/upload_db.ps1"
  - name: Execute export_db.ps1 that export d365fo database from VmA into {{ extract_db_path }}
    win_shell: powershell.exe -File "C:/Temp/export_db.ps1" "{{ extract_db_path }}" "{{ db_name }}"
  - name: Execute upload_db.ps1 that upload extracted db into a blob
    win_shell: powershell.exe -File "C:/Temp/upload_db.ps1" "{{ extract_db_path }}" "{{ db_name }}" "{{ blob_url }}"
    